npmPublishAccess: public

npmScopes:
  sutor:
    npmPublishRegistry: "https://registry.npmjs.org"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.js
    spec: "@yarnpkg/plugin-version"

yarnPath: /Users/daniel.couper/Work/fs-grow/.yarn/releases/yarn-berry.js
